### ISSUE TITLE
Missing Description field in Dynamic route entries screen v17.

### ISSUE THREAD

**Issue by chopsywa** [FreePBX-ContributedModules/dynroute#6]
If I try to add an entry in the Dynamic route entries screen, I get an error as follows.
![image](https://github.com/FreePBX-ContributedModules/dynroute/assets/109642777/7a799ed5-7344-41ea-9308-10aae2a4cac7)
This is because the description field is missing on the page as you can see here.
![image](https://github.com/FreePBX-ContributedModules/dynroute/assets/109642777/e24c3d9c-db21-4890-9503-9fccdc2e747c)
Comparing to v16 data entry screen.
![image](https://github.com/FreePBX-ContributedModules/dynroute/assets/109642777/55cce261-a115-47ff-acae-8b46af90df38)
This is using Dymamic route Edge module on v17 installation on Debian 12 Linux.

**Comment by johnfawcett** [comment]
I inadvertently removed part of the code that was added in V 16.0.4 from PAULWOOTTON https://github.com/FreePBX-ContributedModules/dynroute/commit/fe07fe02eee92dea03e4a1afbd60a8695d1b3992

I have added back the description field in the entries.php file and added a correction to functions.inc.php to set up a default value for the blank entry, avoiding a php error "undefined array key"

 https://github.com/FreePBX-ContributedModules/dynroute/pull/8

**Comment by kapilgupta01** [comment]
dynaroute v17.0.3
